### ISSUE TITLE
Upgrade pro Exhibit builder 3.0

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#11]
Disponível em: http://omeka.org/add-ons/plugins/exhibit-builder/

**Comment by tamielbr** [comment]
@gabrielfedel Upgrade para 3.1.3 <br>
http://omeka.org/add-ons/plugins/exhibit-builder/

**Comment by tamielbr** [comment]
Acho interessante esperar o desenvolvimento da amarilis e depois damos o upgrade pro 3.1.3, já que não é um "major release". Abaixei prioridade.

**Comment by tamielbr** [comment]
Fazendo a tradução no Transifex, da versão nova, agora há uma funcionalidade que queríamos e antes era um bug: "Começar a exibição na página de resumo. Se não estiver marcado, começar na primeira página se ela existir."

**Comment by gabrielfedel** [comment]
Aguardando a resolução dos bugs relativos ao Upgrade do Omeka para ativar o Exhibit builder 3.0

**Comment by gabrielfedel** [comment]
Foi!
