### ISSUE TITLE
Banco de dados corrompido?

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#110]
Não sei se precisamos re-importar os dados para o Neatline, mas aqui o mapa da cultura apresenta dados todos misturados (dados x, fotos y, etc.). Há backup @gabrielfedel?

**Comment by gabrielfedel** [comment]
você tem algum exemplo desses dados misturados? dei uma olhada rápida aqui e não ví nenhuma inconsistencia

**Comment by gabrielfedel** [comment]
Na verdade achei um que tava posicionado errado, que era a liga humanitária dos homens de cord

**Comment by tamielbr** [comment]
que bizarro. ele faz um "ciclo" antes de mostrar os dados finais e passa por outros dados na janela. parece errado - não sei se vc vê isso ai. talvez é um problema de "cache" ou velocidade de conexão. sim, acho que temos problemas com alguns. vou ter que ver um a um. comecei, mas vai demorar um pouco. ignore o problema então, erro me.
