### ISSUE TITLE
Image layer no Neatline

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#111]
@gabrielfedel tentei usar duas imagens e não consegui. Quando eu coloco a URL, ele não dá load em nada (tela vazia). Você conseguiu?

**Comment by gabrielfedel** [comment]
Quando diz 2 quer dizer 2 ao mesmo tempo?

eu consegui colocar imagem usando uma instalação limpa, não tentei no mapa de Campinas

**Comment by tamielbr** [comment]
Não...tentei com duas imagens diferentes. Estou usando o Tour Afro em Inglês para testar.

**Comment by tamielbr** [comment]
Consegui. Agora estou tentando alinhar as imagens com os pontos. Como a imagem não vem de um servidor WMS, precisa ser feito na mão. Vou continuar testando aqui.

**Comment by tamielbr** [comment]
Comentei aqui pra tentar entender. Fiquei fuçando mas não consigo resolver como integrar a imagem com os pontos. https://github.com/scholarslab/Neatline/issues/370

**Comment by tamielbr** [comment]
Resolvido. Precisamos de GIS, mais pra frente.
