### ISSUE TITLE
Não envia emails para usuários criados com Guest User

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/mapaculturacampinas#116]
É necessário configurar uma conta de smtp no application/config/config.ini

Porém, aparentemente o email pedindo para criar o usuário não é enviado para o administrador...

**Comment by tamielbr** [comment]
@gabrielfedel criar um email genérico qualquer para enviar.

**Comment by tamielbr** [comment]
Passar dados do contato@cultcps.org para @gabrielfedel

**Comment by tamielbr** [comment]
Não vai rolar por hora porque estou usando só o controle no registro de domínio e não vai dar para separar o MX do CNAME. vamos de gmail mesmo pra quebrar o galho ou deixamos sem funcionar por hora (eliminamos). eu mostro no dia e depois tiramos do ar.

**Comment by tamielbr** [comment]
Feito, email criado.
