### ISSUE TITLE
Site responsivo

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#18]
Testato em Android, Iphone, etc.

**Comment by amariliscamargo** [comment]
Testei e também deu certo no ipad e iphone!

**Comment by gabrielfedel** [comment]
Aqui tá ok também!

**Comment by tamielbr** [comment]
@amariliscamargo  - Testando agora, vi alguns problemas específicos (usei meu celular e http://responsivetest.net):
* A janela com a imagem de destaque ficou muito pequena. Podemos diminuir o logo como uma porcentagem? Assim a imagem/destaque ocupa mais espaço como antes?
* "Fale conosco" - o formulário tem rolagem horizontal, podemos resolver isso? Fica difícil de usar no celular.
* Mapas e roteiros fica estranho, não segue o modelo dos "itens", veja a imagem abaixo:<br>
![screen shot 2015-01-15 at 16 11 28](https://cloud.githubusercontent.com/assets/3904166/5768760/3903e4bc-9cd1-11e4-8254-02a4ee58157b.png)

**Comment by amariliscamargo** [comment]
Resolvi o problema das imagens! Testem por favor ;)

**Comment by tamielbr** [comment]
Resolveu das imagens. Vou fechar esse e abrir dois issues novos para as questões pendentes acima, ok? Obrigado!
