### ISSUE TITLE
Arrumar texto em display na página de item

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#19]
1. Precisamos remover, integralmente:
* Título (a palavra e o texto do título, já que ele está no topo das imagens)
* "Abrangência" e o texto abaixo (código) 
* "Idioma" (a palavra e o texto, como "PT_BR") abaixo

2. Precisamos remover os "labels", ou seja as palavras:
* "Descrição" (só deixar o texto em si)

3.Colaborador deve ser "Colaboradores"

4.Adicionar os links para os formatos de saída do Omeka (veja imagem), é padrão do Omeka.

![screen shot 2014-12-03 at 10 09 01](https://cloud.githubusercontent.com/assets/3904166/5282445/6eedbfc2-7ad4-11e4-84cd-464ca02ca4eb.png)

**Comment by amariliscamargo** [comment]
Gente,
Veja se é isso que vocês queriam!

**Comment by tamielbr** [comment]
@amariliscamargo Falta somente arrumar o formato de saída. Queremos como o do Omeka anterior (separado por vírgulas, veja acima na imagem), e não com <li> como está agora, ocupando muito espaço.

**Comment by amariliscamargo** [comment]
Veja se agora, está ok! ;)

**Comment by amariliscamargo** [comment]
Tel essa parte ficou ok?

**Comment by tamielbr** [comment]
Jóia! Valeu.
