### ISSUE TITLE
Design dos comentários

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#20]
Me parece que o espaçamento (em cima, e abaixo) está um pouco grande:
1. Entre a última linha e o header "Comentários"
2. Entre "Comentários" e "comente"
3. Entre "enviar" e o Footer.
![screen shot 2014-12-03 at 10 13 53](https://cloud.githubusercontent.com/assets/3904166/5282537/4c613cee-7ad5-11e4-91d8-044f4bc71d22.png)

Precisamos arrumar também o alinhamento dos comentários em si, veja exemplo: http://mapa.revoada.net.br/items/show/31#comment-3

**Comment by amariliscamargo** [comment]
Corrigi, alinhei os textos. Quanto a cor dos links, só para ter certeza me mande ela em base 10.

**Comment by tamielbr** [comment]
Ficou bom, fechando esse! Vou abrir outro issue pra questão de cores.
