### ISSUE TITLE
Usar social bookmarking plugin

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#22]
Podemos usar a funcionalidade do Plugin do Omeka (Social Bookmarking) que já estava instalado para as funcionalidades de mídias sociais? Ficará bem mais fácil utilizá-lo e configurá-lo dentro do sistema. Imagino que perderemos alguma coisa no design (talvez os contadores de post), mas podemos encontrar um meio-termo.

![screen shot 2014-12-03 at 10 17 20](https://cloud.githubusercontent.com/assets/3904166/5282589/bced9db8-7ad5-11e4-8068-99dc7f98090e.png)

**Comment by amariliscamargo** [comment]
Adicionei o social bookmarking!

**Comment by tamielbr** [comment]
Jóia! Eu removi o que não vamos usar (ícones). Depois alinhamos a posição (centralizado ou esquerda) pendendo de como ficar o mapa logo a cima com a questão do geolocation #48 com @gabrielfedel
