### ISSUE TITLE
ReCaptcha corrigir layout e inglês

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#23]
Na página de Contato, possível mudar texto para português?

![screen shot 2014-12-03 at 10 20 09](https://cloud.githubusercontent.com/assets/3904166/5282622/062203e8-7ad6-11e4-8aed-47ff05d99170.png)

**Comment by amariliscamargo** [comment]
Gente, vocês tiraram o ReCaptcha? Não aparece mais para  mim! :(

**Comment by amariliscamargo** [comment]
Só aparece para enviar mensagem, para comentar, não!

**Comment by tamielbr** [comment]
Aqui aparece: http://mapa.revoada.net.br/items/show/169 mas diminuimos a prioridade disso, porque o recaptcha é problemático no layout.

**Comment by amariliscamargo** [comment]
Ai que bom tel, estava me matando com o ReCaptcha!

**Comment by amariliscamargo** [comment]
Consegui traduzir para o português, testem! ;)

**Comment by tamielbr** [comment]
Legal, o do Recaptcha ainda está em inglês (http://mapa.revoada.net.br/contact) mas é menor prioridade. Esse outro ficou jóia.

**Comment by amariliscamargo** [comment]
Tel aqui está em tudo em português, confirme ai! Bjs

**Comment by tamielbr** [comment]
Legal, fechado.
