### ISSUE TITLE
Redesign da página que aparece com  "Ver exposições" no menu

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#24]
Precisamos rever o design das exposições para que siga o modelo dos outros. Mas antes de tudo, precisamos do upgrade (veja #11).

**Comment by amariliscamargo** [comment]
A página ver exposição, agora ficou igual a ver itens! ;)

**Comment by amariliscamargo** [comment]
Dêem uma olhada se ficou bom! ;)

**Comment by tamielbr** [comment]
Jóia ;)
