### ISSUE TITLE
Mapas e roteiros - Texto abaixo do ícone

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#25]
Poderia ser mais parecido com os outros? Especificamente:
1. Inglês e português poderiam ser opções como na barra da página principal?
![screen shot 2014-12-03 at 10 24 24](https://cloud.githubusercontent.com/assets/3904166/5282707/9ece315c-7ad6-11e4-930d-34f2526911d4.png)
2. Remover "border"
3. Colocar título (direto do "Título" no Neatline) abaixo da imagem. Vamos mudá-las depois.
4. Remover "Mapas e roteiros"

**Comment by amariliscamargo** [comment]
Estou procurando uma função para fazer isso!

**Comment by amariliscamargo** [comment]
Verifiquem se agora ficou correto!

**Comment by tamielbr** [comment]
@amariliscamargo aqui não aparece o texto abaixo dos ícones, como nos itens e exposições.<br>
![screen shot 2015-01-26 at 09 54 46](https://cloud.githubusercontent.com/assets/3904166/5903845/6074f2ac-a541-11e4-9c47-a867b823a899.png)

**Comment by amariliscamargo** [comment]
Oi Tel, coloquei os titulos.

**Comment by tamielbr** [comment]
Jóia.
