### ISSUE TITLE
Box no slider

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#26]
1. Poderíamos alinhar o texto para a esquerda, com um pouco mais de espaçamento (padding).
2. Saiba mais poderia estar sem underline? O vemelho já indica.
![screen shot 2014-12-03 at 10 26 36](https://cloud.githubusercontent.com/assets/3904166/5282787/28cf210e-7ad7-11e4-910d-02681ced11d1.png)

**Comment by amariliscamargo** [comment]
Corrigi, por favor verifiquem se está correto agora. ;)

**Comment by tamielbr** [comment]
Jóia.
