### ISSUE TITLE
Resultado da busca

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#30]
1. Está desconfigurado, precisamos que siga o padrão:
* Ícone, título, descrição
![screen shot 2014-12-03 at 10 51 43](https://cloud.githubusercontent.com/assets/3904166/5283238/646ea448-7ada-11e4-9e90-03a55b6cfc71.png)
<br><br>
2. Necessário customizar e embelezar o texto que aparece acima:
Resultado da pesquisa (XX-XX total), _padronizar o tamanho do texto_
<br><br>
3. Texto abaixo, alinhar layout, remover bullets
![screen shot 2014-12-03 at 10 50 01](https://cloud.githubusercontent.com/assets/3904166/5283231/5c7326ce-7ada-11e4-8942-16d213d5f32d.png)

**Comment by amariliscamargo** [comment]
Modifiquei e aqui ficou certinho! ;) Por favor testem!

**Comment by tamielbr** [comment]
@gabrielfedel aqui parece ok, testei e funciona. o Omeka pega o primeiro arquivo (imagem) para aparecer no círculo. Se não há, fica em branco.

**Comment by tamielbr** [comment]
Fechado.
