### ISSUE TITLE
Arrumar erro Omeka Geolocation

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#31]
Itens não aparecem (DB connection error), enviado por email

**Comment by tamielbr** [comment]
@gabrielfedel se puder ver isso antes de quinta, podemos fechar.

**Comment by tamielbr** [comment]
@gabrielfedel  Erro quando ativa o Geolocation<br>
`O Omeka encontrou um erro`
`Zend_Db_Statement_Mysqli_Exception`
`Mysqli prepare error: Table 'omeka.omeka_locations' doesn't exist`

**Comment by gabrielfedel** [comment]
Tentar descobrir se o plugin cria a tabela, se sim usar a estrutura para criar a tabela

Tentar também apagar o plugin completamente e reinstala-lo

**Comment by gabrielfedel** [comment]
Atualizei, resolveu o problema. Porém aparentemente ele não puxa os dados do Geolocation, imagino que ele puxa de outra tabela... =( vou fechar essa e e abrir uma específica
