### ISSUE TITLE
Manter Github Atualizado

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/mapaculturacampinas#32]
@amariliscamargo e @tamielbr , atualizei tudo que estava no server pro github (com excessão de alguns arquivos, que imagino não sejam necessários, eles estão indicados abaixo).

@amariliscamargo , se por acaso souber usar o git, e quiser pode ir atualizando conforme acertar os detalhes de implementação fique a vontade, caso contrário eu mesmo vou dando os push ;)

**Comment by gabrielfedel** [comment]
Basicamente o quê temos de diferente é o nosso tema e o neatline modificado.

Por hora pensei em deixar tudo pra ficar integrado, mas podemos modificar isso mais pra frente deixando somente o tema e o neatline mesmo

**Comment by tamielbr** [comment]
Acho melhor, porque se alguém quiser instalar temos que explicar que só precisa do tema, e (no readme) explicar modificações no core. senão ficamos presos com qualquer update do neatline.

**Comment by tamielbr** [comment]
Feito no github.com/revoada/guarani
