### ISSUE TITLE
Label do Lightbox incompleto

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/mapaculturacampinas#33]
Quando clica na imagem, o label do lightbox deveria aparecer com as informações da imagem, conforme a versão anterior  - http://perseus.nied.unicamp.br/omeka/items/show/32

**Comment by gabrielfedel** [comment]
@amariliscamargo não sei se entendi qual index perguntou

**Comment by tamielbr** [comment]
@gabrielfedel @amariliscamargo parece que está funcionando. Fechamos esse? A última troca acima, não entendi ;)
