### ISSUE TITLE
Itens recentes na página principal

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#38]
Alguma razão porque só temos 2? Acho que seria bom ter no mínimo o preenchimento horizontal (4) ou idealmente os 8 últimos. O mesmo valeria para exposições em destaque (que serão menos, mas poderia chegar ao máximo de 8).

![screen shot 2014-12-09 at 20 58 45](https://cloud.githubusercontent.com/assets/3904166/5369732/57bf3224-7fe6-11e4-9125-e334e937a9e4.png)

**Comment by amariliscamargo** [comment]
Gente, corrigi isso, deixei somente os 4 ultimos, para não ficar sobrecarreagado o index. ;)

**Comment by amariliscamargo** [comment]
E aparece os recentes, independente de ser destaque ou não!

**Comment by tamielbr** [comment]
@gabrielfedel aqui funcionou, confirma?

**Comment by gabrielfedel** [comment]
Aqui também!
