### ISSUE TITLE
Exposições em destaque

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#41]
Deixei 2 exposições marcadas como "Destaque" no Omeka, mas somente uma aparece na principal. A página principal está buscando as exposições marcadas? Parece um problema similar com esse dos itens #38. Creio que é fácil descobrir itens e exposições em destaque no DB do omeka.

**Comment by amariliscamargo** [comment]
Estou pesquisando uma função que faça isso, pois todos os templates us uma função radômica que só exibe uma exposição em destaque por vez. :(

**Comment by amariliscamargo** [comment]
Consegui! Criei do zero, pois não achei nada parecido em lugar algum! ;)
Testem

**Comment by tamielbr** [comment]
@gabrielfedel aqui parece ok! só dá problema quando uma exposição tem mais de uma "Página" como o MIS-Campinas. Nesse caso, o tema não parece conseguir pegar uma imagem. @amariliscamargo,será que isso é simples?

**Comment by tamielbr** [comment]
Resolvido!
