### ISSUE TITLE
Banner com imagem grande demais

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#42]
@amariliscamargo parece que temos um problema com a imagem selecionada. Veja o site principal agora (http://mapa.revoada.net.br/). Acontece que ao que parece, o banner da página pega a primeira imagem do "item". nesse caso (carlos gomes), era um banner que você criou com um tamanho específico. Quando mudei a ordem da imagens no item (carlos gomes) o banner agora não dimensiona a imagem e pega ela por completo. Precisamos que esse banner consiga pegar a imagem de destaque e dimensione corretamente...

**Comment by amariliscamargo** [comment]
Tel e Gabriel,
o máximo que pude fazer em relação a isso, foi um crop com css. Mas tem que deixar referenciado para quem fazer download do tema, que a primeira imagem, será o banner e que tem que ser uma imagem grande.
A altura deve ser maior que 460px.
Testem!

**Comment by tamielbr** [comment]
Ok, isso resolve!
