### ISSUE TITLE
Clicar em exposições não abre exposição

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#43]
@amariliscamargo, quando clico numa exposição, como por exemplo "Você conhece esse lugar?", aparece o texto, mas a exposição ("Página" na linguagem do Omeka/admin) em si, com fotos, etc. Não aparece. Pode ser relacionada a questão #41.

**Comment by amariliscamargo** [comment]
Vou verificar! :(

**Comment by amariliscamargo** [comment]
Consegui programar para pegar html e css do exhibit do nosso tema! Dêem uma olhada. Estou acertando isso agora! ;)

**Comment by tamielbr** [comment]
Ficou bom! Algumas pequenas questões do "exhibits" vou abrir em separado.
