### ISSUE TITLE
Problema no Banco de Dados/Mysql

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/mapaculturacampinas#44]
Está acontecendo de maneira recorrente o banco de bados parar de funcionar e ser necessário reiniciar o mysql. Verificar os logs do omeka e do Mysql para descobrir o quê pode ser

**Comment by tamielbr** [comment]
@gabrielfedel aumentou memória alocada, vamos aguardar para verificar se é o problema.
