### ISSUE TITLE
Exposição com mais de 1 página não aparece imagem em destaque

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#45]
Veja exemplo do do MIS-Campinas que não tem imagem.<br>
![screen shot 2015-01-15 at 09 22 01](https://cloud.githubusercontent.com/assets/3904166/5761337/0455f716-9c98-11e4-80dd-dc30098b9e4b.png)
As exposições permitem que existam mais de uma "página". O MIS Campinas tem duas páginas e o sistema parece não saber pegar a imagem. O "você conhece esse lugar" é uma página só, e não tem problemas. O sistema só precisa pegar a primeira imagem da primeira página, deve ser simples.

**Comment by amariliscamargo** [comment]
Eu fiz teste com duas páginas nas exposições, o problema se resolveu, mesmo com duas páginas, quando eu salvei de novo e o omeka criou thumbs.
Quando aparece thumbs, aparece as imagens na home.
![exhibts](https://cloud.githubusercontent.com/assets/7985370/5764371/a7240dee-9cd8-11e4-818e-259e45f20823.jpg)

**Comment by tamielbr** [comment]
@gabrielfedel parece que está ok tanto em Firefox 34/Chrome! 
Se aparecer ok pra você, fecha?

**Comment by tamielbr** [comment]
Fechado.
