### ISSUE TITLE
Erro no "Sobre o projeto"

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#46]
Click no "sobre o projeto" e verá erros. Ele tem que ignorar se não houver título/subtítulo.<br>
`Notice: Undefined variable: title in /var/www/revoada/mapaculturacampinas/omeka/themes/cultcampinas/simple-pages/page/show.php on line 13`
`Notice: Undefined variable: subtitle in /var/www/revoada/mapaculturacampinas/omeka/themes/cultcampinas/simple-pages/page/show.php on line 16`

**Comment by amariliscamargo** [comment]
Verifiquem! ;)

**Comment by tamielbr** [comment]
Sumiu, mas agora temos uma barra escura no topo em cinza (Firefox 34): 
![screen shot 2015-01-15 at 12 25 36](https://cloud.githubusercontent.com/assets/3904166/5764746/afcf728e-9cb1-11e4-8514-2838f06ee3f2.png)
<br>mas não no Chrome:
![screen shot 2015-01-15 at 12 26 35](https://cloud.githubusercontent.com/assets/3904166/5764762/ce5f85ea-9cb1-11e4-95e2-ed2551b76a38.png)

**Comment by amariliscamargo** [comment]
Desculpe, isso foi falha minha, a barra do admin tinha sumido, por isso essa lacuna! Mas já corrigi!

**Comment by tamielbr** [comment]
Jóia!
