### ISSUE TITLE
Arrumar espaçamento no Comentários

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#47]
Diminuir margem (espaço) entre o ítens de saída e o header "Comentários". É bom ter espaço ,mas está grande demais e fica estranho.
![screen shot 2015-01-15 at 09 55 54](https://cloud.githubusercontent.com/assets/3904166/5762073/c8b85988-9c9c-11e4-99b2-38394ae0158f.png)

**Comment by amariliscamargo** [comment]
Por favor, verifiquem agora! ;)

**Comment by tamielbr** [comment]
Legal! Agora acho que só falta ajustar para que fique mais como o layout enviado:<br>
![coment](https://cloud.githubusercontent.com/assets/3904166/5765031/9797499c-9cb3-11e4-992c-63f3c258a00d.png)<br>
Me parece que o espaçamento da direita do texto está restrito. Podemos fazer com que  texto do comentário vá (até a direita) alinhando com o texto da descrição?

**Comment by amariliscamargo** [comment]
Oi tel,
veja se agora está correto! ;)

**Comment by tamielbr** [comment]
Jóia.
