### ISSUE TITLE
Fazer o Geolocation puxar os dados de Abrangência

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/mapaculturacampinas#48]

**Comment by tamielbr** [comment]
@gabrielfedel, precisamos avançar aqui pra @amariliscamargo poder mudar a imagem que está de "placeholder" por lá Você tem tempo de olhar isso essa semana em algum momento? Precisa de apoio? Posso dar uma força.<br>
![screen shot 2015-02-06 at 13 05 02](https://cloud.githubusercontent.com/assets/3904166/6086664/cea848a6-ae00-11e4-9035-6633222e4bf4.png)

**Comment by gabrielfedel** [comment]
Tel, estava olhando agora, e aparentemente o geolocation não vai puxar automaticamente os dados de abrangência mesmo

o quê eu posso fazer é um script pra converter os dados de wkt pra lat, long e inserir na localização do geolocation, o quê acha? e depois posso estudar uma maneira de adaptar o plugin pra puxar esses dados

além disso, precisaria gerar uma visualização de onde o item está no mapa certo?

**Comment by tamielbr** [comment]
Recapitulei aqui e temos duas coisas distintas:

1. O plugin to Geolocation do Omeka: http://omeka.org/add-ons/plugins/geolocation/
2. O Neatline Features: http://omeka.org/add-ons/plugins/neatlinefeatures/

O que queremos é o NeatlineFeatures, que faz essa conexão. O Geolocation usa Google Maps e é algo separado. Veja: https://github.com/scholarslab/Neatline/issues/148 -> "And as Wayne said, Neatline seamlessly ingests any coverage data added to an item by way of the Neatline Features plugin".

Faz sentido?

**Comment by gabrielfedel** [comment]
Hum, acho que entendi

eu inseri o neatline features

tentei fazer um teste mas não sei se fui bem sucedido, dá uma olhada

mas além disso, no lugar onde está o ícone, era pra aparecer o quê ? o mapa do geolocation?

**Comment by tamielbr** [comment]
Testei e funciona, uma boa notícia. Veja no Omeka, criei dois itens:

1. No http://mapa.revoada.net.br/admin/items/show/169
2. No http://mapa.revoada.net.br/admin/items/show/170, eu coloquei os dados: "GEOMETRYCOLLECTION(POINT(-5238700.2255714 -2620637.2707878))" SEM clicar em "usar o mapa". 

Depois fui no Neatline e criei "Teste Neatline Features". Importei os dois. Ambos apareceram no mapa do Neatline. Quer dizer, ele importa o Geometrylocation e também importa se você "desenhar" um ponto (com o lápis) no Omeka, na mão, e faz a conversão para WKT.

Agora, precisamos que o "mapa" (quando alguém inserir um item, e clicar em ""usar o mapa") apareça no lugar do icone "Veja no Mapa" que agora aparece. Eu não consegui testar aqui, porque o template não mostra o mapa na página de itens agora.

**Comment by tamielbr** [comment]
Conclusões:
1. Funciona tanto com acima (colocando o texto formatado corretamente com GEOMETRY...
2. Tanto quanto escolhendo o item colocando um ponto no mapa.
