### ISSUE TITLE
Cores das fontes

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#49]
Precisamos que as fontes sigam um padrão único. Links precisam seguir um padrão. 
* Na página principal, o "SAIBA MAIS" pode manter-se em vermelho, conforme o layout. 
Mas veja o exemplo (http://mapa.revoada.net.br/items/show/169). 
* Temos o texto ("atom, dcmes-xml, json, omeka-json, omeka-xml") em azul,
* e o "Responder" que é um link, em verde. 
Podemos manter todos esses links com o azul escuro do padrão da paleta enviada?<br>
![screen shot 2015-01-15 at 12 33 58](https://cloud.githubusercontent.com/assets/3904166/5764924/d1b511aa-9cb2-11e4-9b75-c93338d996c2.png)
<br><br>O mesmo vale para os links no texto:<br>
![screen shot 2015-01-15 at 12 36 42](https://cloud.githubusercontent.com/assets/3904166/5764982/37060780-9cb3-11e4-8921-8fc54c662d1a.png).

**Comment by tamielbr** [comment]
O importante é dar uma olhada geral em todas as páginas para garantir que estamos seguindo um padrão ;)

**Comment by amariliscamargo** [comment]
Olhei tudo, mas as vezes escapa alguma coisa! Por favor verifiquem se está ok!

**Comment by tamielbr** [comment]
Aqui o "Responder" continua verde (testei em Firefox e Safari).

**Comment by amariliscamargo** [comment]
"Arrumei" o Responder! ;)

**Comment by tamielbr** [comment]
Jóia. Vou fechar e depois fazemos na fase final, ajustes, se encontrarmos inconsitências nas fontes/cores.
