### ISSUE TITLE
Barra "Buscar" não está igual

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#5]
Parece que não está pegando o CSS
![screen shot 2014-10-28 at 16 32 43](https://cloud.githubusercontent.com/assets/3904166/4818368/66edc784-5ef2-11e4-8b85-f2ebbf2e5eab.png)
![screen shot 2014-10-28 at 16 32 38](https://cloud.githubusercontent.com/assets/3904166/4818369/66ef967c-5ef2-11e4-9cdb-7065cd16c999.png)

**Comment by amariliscamargo** [comment]
Tamiel,
esse layout não está aceitando essa funcionalidade.
Eu fiz mas ficou feio. :(

**Comment by tamielbr** [comment]
Podemos implementar de outra maneira? Com um "busca avançada" em texto abaixo ou algo similar?

**Comment by amariliscamargo** [comment]
Eu criei um link com o texto busca avançada abaixo do formulario de busca no header que direciona para página de busca avançada! ;)

**Comment by tamielbr** [comment]
Que jóia! Ficou muito bom. Acho que só falta finalizar o style, tá tudo um pouco "amassado" :) 
![screen shot 2015-01-14 at 08 19 37](https://cloud.githubusercontent.com/assets/3904166/5741076/204b7fea-9bc6-11e4-9135-f032bc06857c.png)

**Comment by amariliscamargo** [comment]
Veja agora! ;)

**Comment by tamielbr** [comment]
Ficou ótmo. Eu só arrumaria as caixinhas (selecione abaixo) para ter maior espaçamento vertical, porque o texto ficou comprimido e fechamos esse :)

**Comment by amariliscamargo** [comment]
ok

Em 14 de janeiro de 2015 14:30, Tel <notifications@github.com> escreveu:

> Ficou ótmo. Eu só arrumaria as caixinhas (selecione abaixo) para ter maior
> espaçamento vertical, porque o texto ficou comprimido e fechamos esse :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gabrielfedel/mapaculturacampinas/issues/5#issuecomment-69944251>
> .
>



--

**Comment by amariliscamargo** [comment]
Qual navegador vc está usando?

Em 14 de janeiro de 2015 14:58, amarilis camargo <amariliscamargo@gmail.com>
escreveu:

> ok
>
> Em 14 de janeiro de 2015 14:30, Tel <notifications@github.com> escreveu:
>
>> Ficou ótmo. Eu só arrumaria as caixinhas (selecione abaixo) para ter
>> maior espaçamento vertical, porque o texto ficou comprimido e fechamos esse
>> :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gabrielfedel/mapaculturacampinas/issues/5#issuecomment-69944251>
>> .
>>
>
>
>
> --
>
>


--

**Comment by tamielbr** [comment]
Firefox.

**Comment by amariliscamargo** [comment]
Verifique agora! ;)

**Comment by tamielbr** [comment]
Ficou muito bom. Só faltam duas coisas. O botão ainda está comprimido (como "adicionar um campo", texto muito apertado), acho que vc mudou só o pull-down. E o texto, temos novamente em duas cores (vermelho e preto) e tamanhos diferentes, podemos padronizar isso? Parece relacionado ao #20. Queremos manter um padrão de cores para o site. O vermelho é link (como na página principal, no SAIBA MAIS) e aqui ele apece como texto simples.
![screen shot 2015-01-14 at 10 41 39](https://cloud.githubusercontent.com/assets/3904166/5744003/5ccfb864-9bda-11e4-9b2f-52fad67f3ba6.png)

**Comment by amariliscamargo** [comment]
Nossa que mancada com o vermelho, desculpa Tel, deu branco! :P 
Acho que agora arrumei o botão!

**Comment by tamielbr** [comment]
Ficou verde agora, mas o botão tá igual no Firefox. Veja abaixo:
<br>Firefox</br>
![screen shot 2015-01-14 at 11 10 13](https://cloud.githubusercontent.com/assets/3904166/5744439/0f7867d8-9bde-11e4-88bd-2189fed0e722.png)
<br>Chrome<br>
![screen shot 2015-01-14 at 11 10 59](https://cloud.githubusercontent.com/assets/3904166/5744444/1922ea10-9bde-11e4-8cf9-20a3b8fb034e.png)

**Comment by amariliscamargo** [comment]
Tel qual versão firefox que você está usando? Porque para mim, no firefox, o botão está igual a imagem do google que você mandou.
Qualquer coisa uso hack.

**Comment by tamielbr** [comment]
Estou na 34.0.5, Fedel testou no dele (Linux) e deu mesmo problema 35.

**Comment by gabrielfedel** [comment]
Oi @amariliscamargo , a versão que deu problema com o tel é a 34.05, aqui na 35 parece ok!

**Comment by amariliscamargo** [comment]
ok

**Comment by amariliscamargo** [comment]
Testei em vários lugares (e também no linux e mac) e edtá bom! Testem novamente por favor!

**Comment by tamielbr** [comment]
No Firefox 35.0.1 continua, veja:<br>
![screen shot 2015-01-26 at 09 44 03](https://cloud.githubusercontent.com/assets/3904166/5903714/887b6192-a540-11e4-8c8f-672dd3e81609.png)<br>
![screen shot 2015-01-26 at 09 43 57](https://cloud.githubusercontent.com/assets/3904166/5903716/8c232d34-a540-11e4-9802-3a71f0078357.png)

**Comment by tamielbr** [comment]
@amariliscamargo retomando esse. Só pra ver se é algo que dá pra arrumar. Se for complicado, não é um problema sério e fechamos esse por hora. Pode ser uma incompatibilidade de browsers mesmo.

**Comment by amariliscamargo** [comment]
Tel, virei do avesso isso, se eu mudo no antigo muda no novo! :(
E eu detesto usar hack. :(

**Comment by tamielbr** [comment]
Fica assim então, não tá ruim. Valeu!
