### ISSUE TITLE
Mapas e roteiros não segue o modelo

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#50]
@amariliscamargo Parece que os icones do "Mapas e Roteiros" (http://mapa.revoada.net.br/exhibits) não segue o modelo da página de itens. Isso parece levar ao problema que vemos no #18 com o site responsivo.<br> 
Havia comentado em outro issue - não podemos fazer isso seguir o mesmo modelo de todos os outros com ícone e texto abaixo, tudo seguindo o mesmo padrão?

**Comment by amariliscamargo** [comment]
Estou estudando uma maneira de trazer o layout do exhibits para dentro do tema cult campinas e não alterar no plugin, para evitar erros ao atualizar! ;)

**Comment by amariliscamargo** [comment]
Eu coloquei o Neatline no nosso tema também! Agora para alterar o layout deve ir na pasta neatline>exhibits dentro do tema cultcampinas ;).
Por favor verifiquem se agora ficou bom o responsivo! ;)

**Comment by tamielbr** [comment]
Jóia! Eu consigo ver o mapa dentro do responsivo. Vamos precisar depois (isso nós, não você @amariliscamargo) achar um jeito de melhorar a navegação do mapa dentro do tema.
