### ISSUE TITLE
Menu aparece no lugar errado (Safari)

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#52]
Veja (Safari 7.1.2/Mac), isso em tela cheia, sem compressão.<br>
![screen shot 2015-01-26 at 09 51 18](https://cloud.githubusercontent.com/assets/3904166/5903793/04cea2d6-a541-11e4-90f9-e99d7d11c704.png)

**Comment by amariliscamargo** [comment]
Nossa, vou olhar!!!!! :P

**Comment by amariliscamargo** [comment]
Resolvido! ;)
