### ISSUE TITLE
Responsivo: Barra de imagem está pequena demais

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#53]
No site responsivo, a imagem de destaque pode ocupar maior espaço. Está pequena demais agora. Podemos reduzir o espaço/tamanho do ícone (CultCampinas) e dar mais espaço para a imagem no site responsivo?<br>
![screen shot 2015-01-26 at 09 57 22](https://cloud.githubusercontent.com/assets/3904166/5903926/d4df25a4-a541-11e4-90b0-8c7cd433af9c.png)

**Comment by amariliscamargo** [comment]
Dei uma estudada em sliders responsivo e todos os sites escondem ele quando a imagem fica muito pequena.
Fiz isso e acho que melhorou.
O omeka bloqueia o tamanho do logo.
Quando eu tentava redimensionar, ele automaticamente lançava outra imagem acima e distorcida.
A melhor solução encontrada para celulares, foi manter o logo e tirar o slider.

**Comment by tamielbr** [comment]
Acho elegante a solução de eliminar o slider se o tamanho diminui. Testando aqui, quando chega no tamanho horizontal do logo, ele some. Ficou ótimo. Agora acho que daria pra diminuir o header (vermelho). O problema pra mim é que quase metada de tela é logo + header (vermelho). Conseguimos deixar isso mais enxuto? @amariliscamargo alguma sugestão?

**Comment by amariliscamargo** [comment]
Vou tentar alterar ela! ;)

**Comment by amariliscamargo** [comment]
Oi Tamiel, 
eu reduzi o topo e a imagem, funciona até 236px! ;)

**Comment by tamielbr** [comment]
Legal!
