### ISSUE TITLE
Responsivo: Formulário tem rolagem horizontal

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#54]
"Fale conosco", formulário tem rolagem horizontal, e perde o menu (ele "sai da tela").  Fica difícil de usar no celular.

**Comment by amariliscamargo** [comment]
Deixei o recaptcha responsivo e o campo textarea também! Problema resolvido ;)

**Comment by tamielbr** [comment]
Aqui funciona "quase" :) Veja anexo do http://responsivetest.net/ (no meu Android, igual).
![screen shot 2015-02-02 at 18 29 12](https://cloud.githubusercontent.com/assets/3904166/6035490/c5967dd4-abf1-11e4-8c29-133058d8ec9f.png)

**Comment by amariliscamargo** [comment]
Eu refiz a programação e aqui sumiu a barra de rolagem horizontal! Testem por favor!

**Comment by tamielbr** [comment]
Legal, em alguns ainda acontece, bem pequeno, mas acho que não é nada essecial. Podemos só eliminar esse borders cinzas ao redor do formulário e do captcha? E fechamos isso ;)

**Comment by amariliscamargo** [comment]
Pronto tirei as tabelas! ;)
