### ISSUE TITLE
Centralizar e padronizar fontes nas exibições

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#55]
Queremos novamente seguir o padrão de todos os itens (fonte e centralização).<br>Aqui está com fonte pequena e não centralizada (http://mapa.revoada.net.br/exhibits/show/mis/mis-rosario-1890-1990)<br>
![screen shot 2015-01-26 at 10 05 14](https://cloud.githubusercontent.com/assets/3904166/5904057/f03057be-a542-11e4-98e3-0f71652e4d78.png)<br><br>
Aqui está centralizado, mas com fonte pequena (http://mapa.revoada.net.br/exhibits/show/mis/catetral)<br>
![screen shot 2015-01-26 at 10 05 49](https://cloud.githubusercontent.com/assets/3904166/5904066/ff71997c-a542-11e4-8701-0b08283ca96c.png)

**Comment by amariliscamargo** [comment]
Centralizei
