### ISSUE TITLE
Responsivo: Ícones aparecem amassados/exibições

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#56]
Não sei se é um único template que toma conta de todos os formatos das exposições, já que o Omeka tem vários "modelos" que podem ser aplicados para criar exibições. Me avise se isso for muito complicado e conversamos. Mas veja um exemplo - precisamos aplicar o mesmo formato para a aparência dos ícones no celular. Veja o que acontece no http://mapa.revoada.net.br/exhibits/show/mis/catetral:<bR>
![screen shot 2015-01-26 at 10 10 13](https://cloud.githubusercontent.com/assets/3904166/5904114/8c3a7f90-a543-11e4-8bcc-9f0d80f9c0be.png)

**Comment by amariliscamargo** [comment]
Tel,
já desmembrei o exhibit e não consigo alterar esse modo de exibição.
Andei pesquisando e isso é um problema a ser resolvido pelo plugin, pois há vários usuários reclamando por não ser responsivo.
Não sei se numa futura atualização eles melhorem isso!

**Comment by tamielbr** [comment]
Ah, ok... você manda os links que achou que apontam os problemas? Assim depois nós podemos acompanhar.

**Comment by tamielbr** [comment]
@gabrielfedel acho que podemos deixar isso, já que é só focado nos exhibits. Se é um bug por hora, paciência. Alguma sugestão?

**Comment by amariliscamargo** [comment]
Tel alguns usuários falaram sobre esse plugin:
https://github.com/sheepeeh/plugin_NALLayouts/tree/master
Diz que torna o exhibit builder responsivo, tentei instalar deu erro, pode ser que eu tenha feito algo errado, vocês querem testar?

**Comment by gabrielfedel** [comment]
Hum... eu instalei o plugin, mas parece que não resolveu...

@tamielbr acho que deixamos assim por hora, e fica como uma resolução futura de problema...

**Comment by amariliscamargo** [comment]
Gabriel, não sei como fiz, mas inventei de alterar no css e deu certo :P

**Comment by tamielbr** [comment]
@gabrielfedel ficaram todos pequenos, mas beeem melhor do que amasados. Por mim, fica assim!
@amariliscamargo  Só ficou um pequeno ajuste no texto (veja abaixo).
![screen shot 2015-02-14 at 19 17 22](https://cloud.githubusercontent.com/assets/3904166/6201852/2d6a3b6e-b47e-11e4-95d4-1a54471d0366.png)

**Comment by amariliscamargo** [comment]
Arrumei, quando atela for muito pequena, joga para outra linha! ;)

**Comment by tamielbr** [comment]
Jóia!
