### ISSUE TITLE
Estilizar o "breadcrumb" das exposições

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#57]
Isso não fez parte da descrição original (não lembramos disso) mas precisamos re-estilizar esse "cinza" para seguir melhor o padrão. Pensei em seguir o background azul-escuro, que acha @gabrielfedel? <br>
http://mapa.revoada.net.br/exhibits/show/mis/catetral<br>
![screen shot 2015-01-26 at 10 13 23](https://cloud.githubusercontent.com/assets/3904166/5904203/21c049aa-a544-11e4-8e9f-965252b5bcc7.png)

**Comment by amariliscamargo** [comment]
Agora está igual dos itens! ;)

**Comment by tamielbr** [comment]
@amariliscamargo ah! não tinha pensado em colocar a imagem de destaque. não sei se há mais nada no site que usa "breadcrumbs" para ver um exemplo. no entanto, é melhor não ter a imagem e simplesmente usar o texto no background azul (veja nesse exemplo).
![screen shot 2015-02-10 at 11 12 44](https://cloud.githubusercontent.com/assets/3904166/6133240/cac69180-b115-11e4-9d7d-38c9b3360a02.png)

**Comment by amariliscamargo** [comment]
Veja se agora ficou melhor?

**Comment by tamielbr** [comment]
Ficou. Deixe-me brincar um pouco mais com as exposições para verificar.

**Comment by tamielbr** [comment]
1. Vamos <b>eliminar barra azul e foto totalmente</b>. Queremos que a exibição seja o foco e agora a imagem não é clicável, não tem propósito. 
2. Deixar o título do jeito que está, preto em verde.
3. Abaixo, <b>vamos eliminar o cinza e manter o fundo verde claro</b> com o “breadcrumb”. 
4. Vamos seguir um <b>formato tradicional</b> no breadcrumb assim: “Nome da exposição >> Nome da página atual”<br>
<br>Agora ele está assim, com o nome da Exposição primeiro, e abaixo com "tab" o nome das <b>duas </b>páginas disponíveis, não fica legal.<br>
![screen shot 2015-02-10 at 12 06 47](https://cloud.githubusercontent.com/assets/3904166/6134274/51c6e480-b11d-11e4-8f2e-d381360a62bc.png)

**Comment by amariliscamargo** [comment]
O omeka que fez essa disposição de breadcumb, eu mudei o css e ficou tudo numa mesma linha, vejam se agora ficou bom! ;)

**Comment by tamielbr** [comment]
Jóia, ficou bem melhor. Acho que só falta o ponto "3" (remover o fundo cinza).

**Comment by amariliscamargo** [comment]
Removi o fundo cinza!;)

**Comment by tamielbr** [comment]
Ok, só falta o 2, acima (links).

**Comment by amariliscamargo** [comment]
Tel, veja se agora ficou ok! Tive que fazer a programação :P

**Comment by tamielbr** [comment]
Ficou bom!
