### ISSUE TITLE
Tamanho do campo maior que tela no responsivo

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#58]
Deve ser rápido, mas no responsivo o tamanho da entrada de texto precisa ser proporcional a tela, veja que sai fora, na "busca avançada".
<br>
![screen shot 2015-02-06 at 10 32 42](https://cloud.githubusercontent.com/assets/3904166/6084192/287c7f9c-adec-11e4-9001-2447dcd981e0.png)

**Comment by amariliscamargo** [comment]
Pronto, ficou responsivo! ;)
