### ISSUE TITLE
Modificar Visualização Mapa

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/mapaculturacampinas#60]
Amarilis, não sei se lembra que mandei pra você um tempo atrás um pedido pra modificar a visualização do mapa (atualmente está assim: http://mapa.revoada.net.br/neatline/show/mapa ), mas gostaríamos de cair em algo que ocupasse mais a tela (praticamente o fullscreen), mas com uma barrinham mais discreta como essa: 

![topo-mapa](https://cloud.githubusercontent.com/assets/2080121/6110640/32be1ac6-b06a-11e4-8c6c-d1f4ebd3618a.jpg)

Pra isso você vai precisar mexer no neatline, acho que você pode trabalhar a partir da visualização fullscreen, pra ficar mais fácil, gerando uma nova view

**Comment by amariliscamargo** [comment]
OK

**Comment by amariliscamargo** [comment]
Veja se ficou bom! ;)

**Comment by tamielbr** [comment]
@amariliscamargo  Eu acho que o que precisamos na verdade é o que o link que inclui o ``/fullscreen`` na URL apareça. 

Sem o fullscreen, o texto aparece somente abaixo:<br>
http://mapa.revoada.net.br/neatline/show/roteiro-centro

Com o fullscreen aparece com o CSS bem formatado:<br>
http://mapa.revoada.net.br/neatline/fullscreen/roteiro-centro

Veja que ele organiza a página direito quando tem o fullscreen, implementado algo que o @gabrielfedel tinha desenvolvido (o texto à esquerda aparece corretamente). Ou seja, a barra está ótima, só precismos que ele vá para essa tela com fullscreen abaixo do banner verde.

@gabrielfedel concorda?

**Comment by tamielbr** [comment]
Ah, o logo aparece sem texto (CultCampinas), não sei se ele está pegando outra imagem?
![screen shot 2015-02-21 at 10 28 22](https://cloud.githubusercontent.com/assets/3904166/6315107/a180c21c-b9b4-11e4-8659-3c268926824e.png)

**Comment by gabrielfedel** [comment]
Na verdade @tamielbr , acho que a melhor ideia é quando ir pra um mapa ou roteiro, fosse direto pro fullscreen, só que com essa barrinha superior (talvez sem a barra inferior)

então a mudança seria em cima da visualização fullscreen amarilis, pra deixar ela com essa barrinha, e não haver uma visualilzação "intermediária"

o quê acham?

**Comment by amariliscamargo** [comment]
Eu procurei dentro do omeka e não encontrei como puxar o fullscreen direto!
Coloquei a imagem com texto para ver se vocês acham melhor!

**Comment by tamielbr** [comment]
@gabrielfedel concordo contigo, acho que dissemos a mesma coisa. Mas a barra inferior é importante deixar, pelos direitos autorais, mesmo do mapa. Mas a superior, concordo. fica legal. Acho que precisamos que o logo tenha o texto completo. 
@amariliscamargo quanto a puxar fullscreen, não basta implementar na URL com /fullscreen (veja acima)?

**Comment by amariliscamargo** [comment]
Gabriel, deixa ver se eu entendi.
Quando clicar nas bolinhas já com o nome do mapa escolhido, vem o fullscreen direto?
Se sim beleza.

**Comment by amariliscamargo** [comment]
Veja se é isso que eu fiz! ;)

**Comment by tamielbr** [comment]
É isso, mas falta só colocar as barras (como tava antes, a verde com logo+menu em cima, e a vermelha, em baixo).

**Comment by amariliscamargo** [comment]
Veja se é assim que é para ficar! ;)

**Comment by tamielbr** [comment]
@amariliscamargo, quase! Veja só o problema aqui na barra inferior.
![screen shot 2015-02-23 at 13 45 51](https://cloud.githubusercontent.com/assets/3904166/6336776/5535aa44-bb62-11e4-8033-0f3c35836356.png)

**Comment by gabrielfedel** [comment]
Aqui no meu também aconteceu um probleminha com o ícone de selecionar a camada de mapa, veja:

![screenshot - 23-02-2015 - 18 32 24](https://cloud.githubusercontent.com/assets/2080121/6338011/813fe0d2-bb8a-11e4-8d5a-6245d93056b3.png)

**Comment by amariliscamargo** [comment]
Por favor, testem para ver se agora está ok! ;)

**Comment by tamielbr** [comment]
@gabrielfedel aqui ok Firefox/Saf/Chr. E ai? @amariliscamargo só pra saber, o código do footer é igual para todos? Se quisermos mudar o texto, é somente um local ou vários?

**Comment by amariliscamargo** [comment]
Oi @gabrielfedel, igual para todos, só o header muda para o neatline, ai vc vai na pasta neatline dentro do tema, procura fullscreen.php e altera lá.
O exhibitsbuilder e o neatline, se precisar vc altera dentro do tema! ;)
