### ISSUE TITLE
Adicionar resumo de exibições na página "ver exibições"

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#61]
Nessa página, http://mapa.revoada.net.br/exhibits: 
Copiar modelo das exposições em destaque, com texto logo abaixo. Como as exposições são poucas, é interessante ter o texto descritivo logo abaixo.<br>
Está assim:
![screen shot 2015-02-10 at 12 01 14](https://cloud.githubusercontent.com/assets/3904166/6134176/928dddf8-b11c-11e4-8d34-31cbc6729b40.png)<br>
Queremos assim:<br>
![screen shot 2015-02-10 at 12 01 23](https://cloud.githubusercontent.com/assets/3904166/6134172/8da62afc-b11c-11e4-96e6-40ebf97e7be1.png)<br>

**Comment by amariliscamargo** [comment]
Pronto Tamiel! ;)
Quando o texto da exposição for muito grande, ele faz resumo automatico!

**Comment by tamielbr** [comment]
;)
