### ISSUE TITLE
Organizar links na página de exibição

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#62]
Veja exemplo: http://mapa.revoada.net.br/exhibits/show/expo-mis
Queremos os links para as páginas (que agora aparecem ao final da página) no começo. Queremos que fique alinhado ao texto (a esquerda) logo no começo, antes do texto:<br>

<b>Páginas da exposição</b> (usando mesma fonte/tamanho que a palavra “Créditos”)
Link da página (alinhado a esquerda, cores da mesma maneira)
Link da página 2 (alinhado a esquerda, cores da mesma maneira)
Link da página 3..., etc. 

Agora está assim:<bR>
![screen shot 2015-02-10 at 12 03 59](https://cloud.githubusercontent.com/assets/3904166/6134215/ea1b5640-b11c-11e4-9b28-48346e9dc3a1.png)

**Comment by amariliscamargo** [comment]
Veja se está como vocês pediram ;)

**Comment by tamielbr** [comment]
Jóia!
