### ISSUE TITLE
Remover texto nas páginas de exposição

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#64]
O texto que aparece nas páginas “Arquivos - XXXXXX” precisa ser eliminado em todas as páginas de exibição. Não tem funcionalidade.<br>
Veja por exemplo em: http://mapa.revoada.net.br/exhibits/show/expo3/p--gina-1
![screen shot 2015-02-10 at 13 41 41](https://cloud.githubusercontent.com/assets/3904166/6136011/91a2d124-b12a-11e4-85aa-1eacd8914ca5.png)

**Comment by amariliscamargo** [comment]
Removi! ;)

**Comment by tamielbr** [comment]
Jóia.
