### ISSUE TITLE
Iframe video aparece muito pequeno nos posts

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#65]
Algo que é novo (não acontecia no outro tema), o vídeo aparece em tamanho reduzido, muito pequeno. É problema de CSS? veja: http://mapa.revoada.net.br/items/show/112

O código no Omeka é:
``` 
<iframe src="//player.vimeo.com/video/79192654" width="320" height="240"></iframe> 
```

**Comment by amariliscamargo** [comment]
Eu corrigi, mas quando a tela for menor que 320px, o video passa o tamanho, pois está fixo no video
width="320" height="240", não sei se tem uma forma de colocar o video sem especificar o tamanho.
Mas eu arrumei o iframe.

**Comment by tamielbr** [comment]
A tela menor, sem problemas. O estranho é que no site aparece "quadrado" mesmo quando o tamanho não é especfiicado ou é maior/retangular. Veja:

Está assim agora, quadrado:<br>
![screen shot 2015-02-12 at 11 25 21](https://cloud.githubusercontent.com/assets/3904166/6174113/fc093e92-b2a9-11e4-8fe0-2d929bc13562.png)

Mas no Omeka, original, está assim, retangular e maior:<br>![screen shot 2015-02-12 at 11 25 27](https://cloud.githubusercontent.com/assets/3904166/6174111/f819013c-b2a9-11e4-8ea1-e4b8bdf08ac3.png)

**Comment by amariliscamargo** [comment]
Gente testem de novo, mas fica a observação, quando a tela for menor que 320px, o video passa o tamanho, pois está fixo no video:
width="320" height="240",

**Comment by tamielbr** [comment]
Perfeito; Removi a especificação (era 500 wide) e funcionou.
