### ISSUE TITLE
Facilitar entrada/sugestão de dados via form

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#67]
Formulário/interface que simplifique/facilite inserção de dados, mesmo via Omeka ou sem.

**Comment by amariliscamargo** [comment]
Tel dá um exemplo para mim!!!!

**Comment by tamielbr** [comment]
Ah, isso não é pra ti @amariliscamargo  ;) Veja que não coloquei o "mediaup" lá no label. Esse é trabalho pra depois. Valeu!

**Comment by amariliscamargo** [comment]
Ok Tel rsrsrsrs 
:P

**Comment by tamielbr** [comment]
Ver exemplo do form aqui: http://grad.geography.wisc.edu/garver/omeka/about

**Comment by tamielbr** [comment]
Migrado para #73.
