### ISSUE TITLE
Ver "tags" retorna página em branco

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#68]
Na página de busca, clicar em "Ver por tags" retorna página em branco.

http://mapa.revoada.net.br/items/search

![screen shot 2015-02-23 at 08 52 07](https://cloud.githubusercontent.com/assets/3904166/6330897/4d4e39b4-bb39-11e4-8f0b-4ed366d789c7.png)

**Comment by amariliscamargo** [comment]
Está funcionando tel! ;)

**Comment by tamielbr** [comment]
Chique!
