### ISSUE TITLE
Alterar imagens dos roteiros

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#76]
@gabrielfedel  você sabe de onde vem as imagens utilizadas em: http://mapa.revoada.net.br/neatline?

**Comment by gabrielfedel** [comment]
As imagens ficam em /var/www/mapaculturacampinas/omeka/imagens

**Comment by gabrielfedel** [comment]
As imagens estão quegradas agora pois não existe a pasta imagens no omeka. Basta criar a pasta e subir as imagens lá dentro

**Comment by gabrielfedel** [comment]
Fica na pasta imagens, dentro do omeka
