### ISSUE TITLE
Atualização do Neatline Text

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#79]
Verificar https://github.com/scholarslab/nl-widget-Text

**Comment by tamielbr** [comment]
Atualizar, a versão é de maio/2015.
http://omeka.org/add-ons/plugins/neatlinetext/
Ele vem com um "tema" básico em CSS que foi feito nos moldes do que @gabrielfedel criou e pode substituir. Há indicação de alguns exemplos mais sofisticados aqui (http://neatline.dclure.org/).

**Comment by gabrielfedel** [comment]
Atualizado
