### ISSUE TITLE
Atualizar Neatline

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/mapaculturacampinas#8]

**Comment by gabrielfedel** [comment]
@tamielbr olha que legal, no novo neatline dá pra acessar direto o item! talvez a gente possa usar isso ao invés do geolocation...
http://mapa.revoada.net.br/neatline/fullscreen/mapa#records/154

**Comment by gabrielfedel** [comment]
@amariliscamargo , só pra avisar, estou mexendo no neatline, se puder segurar um pouco pra mexer nos arquivos dele, já aviso quando terminar

**Comment by amariliscamargo** [comment]
Ok!

Em 15 de janeiro de 2015 16:50, Gabriel Fedel <notifications@github.com>
escreveu:

> @amariliscamargo <https://github.com/amariliscamargo> , só pra avisar,
> estou mexendo no neatline, se puder segurar um pouco pra mexer nos arquivos
> dele, já aviso quando terminar
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gabrielfedel/mapaculturacampinas/issues/8#issuecomment-70139029>
> .
>



--

**Comment by gabrielfedel** [comment]
@tamielbr atualizei, pode dar uma olhada pra ver se deixei passar algo?

@amariliscamargo , terminei fique a vontade para mexer!
