### ISSUE TITLE
Problema com itens no Neatline Text

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/mapaculturacampinas#87]
Quando se clica no item do texto lateral, não aponta para o item no mapa

**Comment by gabrielfedel** [comment]
O problema ocorre devido à alguma mudança no text-public.js (registrei um issue - https://github.com/scholarslab/nl-widget-Text/issues/3), se eu deixar a versão antiga ele funciona.

deixarei com a versão antiga do js até termos uma resposta de quem desenvolve o plugin.

**Comment by tamielbr** [comment]
usando arquivos antigos, aguardando resolução.
