### ISSUE TITLE
Adicionar CC chooser

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/mapaculturacampinas#9]
Depois de feito, Mariana pode atualizar todos os dados. Usa API do CC, melhor do que o feito manualmente como temos agora.

**Comment by tamielbr** [comment]
O pessoal do Omeka Dev fez o upgrade. Parece que era tão fácil que não demorou nada. Vou fazer o upgrade e testar (https://github.com/daniel-km/CreativeCommonsChooser)

**Comment by gabrielfedel** [comment]
Vou instalar e testar

**Comment by gabrielfedel** [comment]
Existe algum problema no plugin, o omeka não está deixando instalar...

vou tentar ver se consigo descobrir com calma o problema

**Comment by tamielbr** [comment]
Se tiver alguma idéia me avise, eu posso perguntar no "dev" (ou veja o link acima).

**Comment by tamielbr** [comment]
O thread no omeka-dev é esse:
https://groups.google.com/forum/#!topic/omeka-dev/-kheqEPHKzg

Assim que você der restart no MySQL eu entro pra testar.

**Comment by gabrielfedel** [comment]
Não consegui mexer mais, mas assim que eu der uma nova olhada já aviso!

**Comment by tamielbr** [comment]
Foi atualizado para 2.3. Já fiz upload e instalei, parece funcionar. Vou testar como funciona na prática.

**Comment by tamielbr** [comment]
Discussão está em desenvolvimento aqui, vamos aguardar: https://github.com/creativecommons/techstuff/issues/17#issuecomment-110169098
