### ISSUE TITLE
Separar o Tema CultCps como um novo repositório

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/mapaculturacampinas#94]
Aparentemente é simples:

https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by tamielbr** [comment]
@gabrielfedel rever arquivos desnecessários, para limpar.

**Comment by tamielbr** [comment]
@gabrielfedel verificar ligações no core.

**Comment by tamielbr** [comment]
Feito.
